apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ilis6pvj7-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:d25b4e5547f808d54c6d7a92e485ed0769fcec08@sha256:45d640e74ff22ef6adc82921485ea2f33c06be3e5d3d221d9a5f06669e57d8d3
          name: container-image
